### ISSUE TITLE
Ordering broke with recent release.

### ISSUE THREAD

**Issue by G3N7** [jimschubert/swagger-codegen-cli.docker#2] opened 2017-03-02 22:07 UTC
I had been relying on the generation to apply alphabetical ordering to my endpoints, however this recently broke, and now the nodes all appear in the order they exist as is.  Please help direct me to resolution.

**Comment by jimschubert** [comment] 2017-03-02 23:04
@G3N7 I don't think this issue is because of this repository. This just builds a docker image off of the current master branch of swagger-codegen whenever a change is pushed to Swagger Generator (https://hub.docker.com/r/swaggerapi/swagger-generator/).  I'm assuming the cause is due to yesterday's 2.2.2 release of swagger-codegen?

If you need to lock down your build to a specific version of Swagger Codegen, and you have bash and Java installed on your machine, you can just use a script such as https://gist.github.com/jimschubert/62baf653a9520b23399a67755c33631a:

```
#!/bin/bash

ver=2.2.0
jar=swagger-codegen-cli-$ver.jar
md5=57e673eb334364ab614cc6083b0f4b27
repo="http://repo1.maven.org/maven2/io/swagger/swagger-codegen-cli/$ver/$jar"

if [ ! -f $jar ]; then
  echo "[info] downloading $PWD/$jar from $repo" 1>&2
  if ! curl --location --silent --fail --remote-name $repo -o $jar; then
    exit 1
  fi
fi

checksum=`openssl dgst -md5 $jar | awk '{ print $2 }'`
if [ "$checksum" != $md5 ]; then
  echo "[error] Bad $PWD/$jar. Delete $PWD/$jar and run $0 again."
  exit 1
fi

java -ea                          \
  $JAVA_OPTS                      \
  -Xms512M                        \
  -Xmx1024M                       \
  -server                         \
  -jar $jar "$@"
```

If you need version 2.2.1, update the above script with:

```
ver=2.2.1
md5=517ff96f59bd160aca0dbe4acb878db3
```

You can grab any version and it's md5 by modifying this command:

```
curl https://repo1.maven.org/maven2/io/swagger/swagger-codegen-cli/2.2.1/swagger-codegen-cli-2.2.1.jar | md5
```

This would obviously change your workflow a bit, because you'd be running that script with the same commands as documented on the swagger-codegen repository.

A caveat, however, is that JSON by definition is an unordered set of key+values. While it sometimes seems safe to rely on key order I have been bitten in the past when expecting order and having unmodified code and JSON result in a different order. This is why I say I don't think it's a result of this repository.

If none of the above is of help (sorry, I was making some assumptions about what you were asking), I'd suggest reviewing the [changes in swagger-codegen 2.2.2](https://github.com/swagger-api/swagger-codegen/releases/tag/v2.2.2) and opening an issue on that repo. It *could* be that a generator previously sorted endpoints prior to generation and in version 2.2.2 it doesn't.

I'll work on getting some tagged versions of 2.2.0 and 2.2.1 implemented in this repository, but I may not get around to it for a few days.

**Comment by G3N7** [comment] 2017-03-03 07:23
Thank you sir for your detailed response and time. 🍺

**Comment by jimschubert** [comment] 2017-03-03 15:36
@G3N7 no problem. Just wanted to let you know, I created tags of the image for 2.2.0, 2.2.1, and 2.2.2: https://hub.docker.com/r/jimschubert/swagger-codegen-cli/tags/  This should allow you to lock down to the previous release version to see if it resolves your issue.

**Comment by G3N7** [comment] 2017-03-03 21:16
Thanks, 2.2.1 worked and got us unblocked.

**Comment by jimschubert** [comment] 2017-03-03 22:24
Cool, glad it worked. I'll go ahead and close this.

**Closed as completed by jimschubert** 2017-03-03 22:24 UTC
